<?php
$title = 'Add new post';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php


$title = $form->get('title');
$title->setAttribute('id', 'title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');

$content = $form->get('content');
$content->setAttribute('id', 'content');
$content->setAttribute('class', 'form-control');
$content->setAttribute('placeholder', 'Content');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($content) ?>
    <?= $this->formElement($content) ?>
    <?= $this->formElementErrors()->render($content, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>




