<?php
// module/Album/view/album/album/index.phtml:

$title = 'My posts';
$this->headTitle($title);
?>


<h1 id="myAlbumsTitle"><?= $this->escapeHtml($title) ?></h1>

<table id="indexTable" class="table">
    <tr>
        <td colspan="3"><a id = "create" class="btn" href="<?= $this->url('admin', ['action'=>'addPost'])?>">Add new post</a></td>
    </tr>
    <tr>
        <th>Title</th>
        <th>Created time</th>
    </tr>
    <?php

    foreach ($posts as $post) : ?>
        <tr>
            <td><?= $this->escapeHtml($post->title) ?></td>
            <td><?= $this->escapeHtml($post->artist) ?></td>
            <td>
                <a class="edit_item_js" href="javascript:void(0);" data-edit-url="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>" >Edit</a>
                <a class="delete_item_js" href="javascript:void(0);" data-delete-url="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id])  ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>