
<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>

<h1 id="myAlbumsTitle"><?= $this->escapeHtml($title) ?></h1>
<div id="edit-form-container"></div>
<div id="delete-form-container"></div>

<table id="indexTable" class="table">
    <tr>
        <td colspan="3"><button id = "create" class="btn">Add new album</button></td>
    </tr>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Action </th>
    </tr>
    <?php

    foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a class="edit_item_js" href="javascript:void(0);" data-edit-url="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>" >Edit</a>
                <a class="delete_item_js" href="javascript:void(0);" data-delete-url="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id])  ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<div id="loadAlbumRegistration" hidden="true">
    <h1 id="addAlbumTitle">Add new Album</h1>
    <?php
    // This provides a default CSS class and placeholder text for the title element:
    $album = $form->get('title');
    $album->setAttribute('id', 'title');
    $album->setAttribute('class', 'form-control');
    $album->setAttribute('placeholder', 'Album title');

    // This provides a default CSS class and placeholder text for the artist element:
    $artist = $form->get('artist');
    $artist->setAttribute('id', 'artist');
    $artist->setAttribute('class', 'form-control');
    $artist->setAttribute('placeholder', 'Artist');

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('id', 'go');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('album', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <?php // Wrap the elements in divs marked as form groups, and render the
    // label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

    <?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();
    ?>
</div>
<script>
    $(document).ready(function(){

        $("#create").on("click", function(event){
            $.ajax({
                url:        '/album/add',

                success: function(response) {
                    $('#myAlbumsTitle').hide();
                    $('#indexTable').hide();
                    $('#loadAlbumRegistration').attr('hidden', false);
                },
                error : function(xhr, textStatus, errorThrown) {
                    alert('Ajax request failed.');
                }
            });
        });


        $(".edit_item_js").on("click", function(event){
            let url = $(this).attr('data-edit-url');
            $.ajax({
                url: url,
                method: 'GET',
                dataType: 'html',
                success: function(response) {
                    $('#edit-form-container').html(response);
                    $('#indexTable').hide();
                    $('#myAlbumsTitle').hide();
                },
                error : function(xhr, textStatus, errorThrown) {
                    alert('Ajax request failed.');
                }
            });
        });

        $(".delete_item_js").on("click", function(event){
            let url = $(this).attr('data-delete-url');
            $.ajax({
                url: url,
                method: 'GET',
                dataType: 'html',
                success: function(response) {
                    $('#delete-form-container').html(response);
                    $('#indexTable').hide();
                    $('#myAlbumsTitle').hide();
                },
                error : function(xhr, textStatus, errorThrown) {
                    alert('Ajax request failed.');
                }
            });
        });

        $("#go").on("click", function(event){

            $.ajax({
                url: "/album/index",
                method: 'POST',
                dataType: 'html',

                success: function(response) {
                    alert("Your entered a new album!");
                },
                error : function(xhr, textStatus, errorThrown) {
                    alert('Ajax request failed.');
                }
            });
        });
    });
</script>
